site_name: Everything Ai
repo_url: https://github.com/demo-ai-labs/MLPipeline
nav:
  - Home: index.md
  - pipeline:
    - train: pipeline/train.md
    - evaluate: pipeline/evaluate.md
    - utils: pipeline/utils.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for any file changes
